year = int(input(" Enter the year:  " ))
genre = (input(" Enter the genre:  " ))
album =(input(" Enter the album:  " ))
songtitle = (input(" Enter the Song Title:  " ))
artist = (input(" Enter the artist: "))

print("-----------------------------")
print("SONG DETAILS")
print("-----------------------------")

print(f"Year Released: {year}")
print(f"Genre: {genre}")
print(f"Album: {album}")
print(f"Title: \"{songtitle}\"")
print(f"Artist: {artist}")
